#!/bin/bash
cd /root 
git clone -b release-stable ${REPO_URL} 
chmod -R +x /root/${REPO_DIR}/install_scripts/
/root/${REPO_DIR}/install_scripts/mkuser.sh
/root/${REPO_DIR}/install_scripts/mkjail.sh
mkdir -p /run/sshd && chmod 755 /run/sshd
/usr/sbin/sshd &
/usr/bin/tail -f