#!/bin/bash

echo "Setting up Repository -----------------------------------------------------"

if [ -d /root/${REPO_DIR} ]; then
    
    echo "Repository exists checking if upto date------------------------------------------"

    cd /root/${REPO_DIR}
    
    if [git pull | grep -q "Already"]; then
            echo "Repository is already up to date"
       else
            /root/sshd_setup
    fi
else
    cd /root 
    git clone -b release-stable ${REPO_URL}

    /root/sshd_setup 
fi

echo "Starting sshd  -----------------------------------------------------"
mkdir -p /run/sshd && chmod 755 /run/sshd
/usr/sbin/sshd &

/usr/bin/tail -f